name: dadoos
description: "A simple, playful dice rolling app built with Flutter."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - assets/images/
#  fonts:
#    - family: GoogleSans
#      fonts:
#        - asset: assets/fonts/GoogleSans-Regular.ttf
  uses-material-design: true

flutter_native_splash:

  color: "#FFE3EF"
  image: assets/splash_screen.png
  fullscreen: true

  android_12:
    color: "#FFE3EF"
    color_dark: "#FFE3EF"
    image: assets/icon.png
    image_dark: assets/icon.png