name: dadoos
description: "my card"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
flutter:
  assets:
    - assets/images/
#  fonts:
#    - family: GoogleSans
#      fonts:
#        - asset: assets/fonts/GoogleSans-Regular.ttf
  uses-material-design: true

#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon.png"